// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Lavanderia_Beatriz_App.Models;

public partial class Acolchado
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public decimal PrecioUnitario { get; set; }

    public int IdTamanio { get; set; }

    [JsonIgnore]
    public virtual Tamanio IdTamanioNavigation { get; set; }
}