// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lavanderia_Beatriz_App.Models;

public partial class EncargadosRecep
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Alias { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public bool Estado { get; set; }

    public int IdPuesto { get; set; }

    public virtual TiposPuesto IdPuestoNavigation { get; set; }
}